#=~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
#
#   Project      : MAGEMinApp
#   License      : GNU GENERAL PUBLIC LICENSE Version 3, 29 June 2007
#   Developers   : Nicolas Riel, Boris Kaus
#   Contributors : Nerone, S., Dominguez, H., Moyen, J-F.
#   Organization : Institute of Geosciences, Johannes-Gutenberg University, Mainz
#   Contact      : nriel[at]uni-mainz.de
#
# ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ =#

function get_contributors()

    debug   = "**Main developer**\n"
    debug   *= "Nicolas Riel\n\n"

    debug   *= "**Debugging and Additions**\n"
    debug   *= "Alexandre Peillod\n"
    debug   *= "Animesh Gorai\n"
    debug   *= "Anton Popov\n"
    debug   *= "Bo Huang\n"
    debug   *= "Boris Kaus\n"
    debug   *= "Ding Chenlong\n"
    debug   *= "Hugo Dominguez\n"
    debug   *= "Hendrik Ranocha\n"
    debug   *= "Jamison Assunção\n"
    debug   *= "Jean-François Moyen\n"
    debug   *= "Joshua Laughton\n"
    debug   *= "Jun Ren\n"
    debug   *= "Lorenzo Candioti\n"
    debug   *= "Nickolas Bardi Moccetti\n"
    debug   *= "Owen Weller\n"
    debug   *= "Pascal Aelig\n"
    debug   *= "Paul Tackley\n"
    debug   *= "Peter Luffi\n"
    debug   *= "Philip Hartmeier\n"
    debug   *= "Pierre Lanari\n"
    debug   *= "Qiaozhi Liang\n"
    debug   *= "Renato Moraes\n"
    debug   *= "Richard Palin\n"
    debug   *= "Simon Schorn\n"
    debug   *= "Tim J.B. Holland\n"
    debug   *= "Tobias Keller"

    app      = "**Interface Suggestions**\n"
    app     *= "Alexandre Peillod\n"
    app     *= "Boris Kaus\n"
    app     *= "Brendan Dyck\n"
    app     *= "Buchanan Kerswell\n"
    app     *= "Cerine Bouadani\n"
    app     *= "Chris Yakymchuk\n"
    app     *= "Dinarte Lucas\n"
    app     *= "Ding Chenlong\n"
    app     *= "Dimitrios Moutzouris\n"
    app     *= "Evangelos Moulas\n"
    app     *= "Guillaume Duclaux\n"
    app     *= "Honghui Wang\n"
    app     *= "Ian Cawood\n"
    app     *= "Jacob Forshaw\n"
    app     *= "Jean-François Moyen\n"
    app     *= "Joan Reche Estrada\n"
    app     *= "Martin Miranda Muruzabal\n"
    app     *= "Nathwani Chetan Lalitkumar\n"
    app     *= "Mohammad Humand\n"
    app     *= "Nicholas Lucas\n"
    app     *= "Olivier Namur\n"
    app     *= "Owen Weller\n"
    app     *= "Pascal Aellig\n"
    app     *= "Paul Tackley\n"
    app     *= "Peter Luffi\n"
    app     *= "Pierre Lanari\n"
    app     *= "Qiaozhi Liang\n"
    app     *= "Renato Moraes\n"
    app     *= "Renee Tamblyn\n"
    app     *= "Simon Schorn\n"
    app     *= "Yishen Zhang\n"
    app     *= "Zeling Wang"

    # contact  = "**Links**\n"
    contact  = "[Tutorials](https://computationalthermodynamics.github.io/MAGEMin_C.jl/dev/)\n"
    contact *= "[Post issue](https://github.com/ComputationalThermodynamics/MAGEMinApp.jl/issues)\n"
    contact *= "[Open discussion](https://github.com/ComputationalThermodynamics/MAGEMin/discussions)\n"
    contact *= "[Discord](https://discord.gg/fjmVZyej9F)"

    # descri  = "**Comments**\n"
    descri  = "Set of examples on how to use MAGEMinApp\n"
    descri *= "Something is not working properly?\n"
    descri *= "Need additional options?\n"
    descri *= "... or join our Discord!"

    return debug,app,contact,descri
end

function get_pkg_versions()
    # retrieve MAGEMin version number info
    return string(pkgversion(MAGEMinApp)), get_MAGEMin_version(), string(pkgversion(MAGEMin_C))
end

function get_ph_list()

    # hidden phases
    hidden_pp = vcat("O2", ALWAYS_ACTIVE_PP)

    # generated by MAGEMin_C from the library + the Warr (2021) mapping + SOLVUS_FAMILY
    magemin_dir = joinpath(pkgdir(MAGEMin_C), "julia")
    dict_em     = JSON.parsefile(joinpath(magemin_dir, "em_name.json"))
    dict_ss     = JSON.parsefile(joinpath(magemin_dir, "ss_name.json"))

    file_path   = joinpath(pkg_dir,"src","./tools/OL12_KDs_g52l63.json")
    dict_OL12_KDs_g52l63     = JSON.parsefile(file_path)
    file_path   = joinpath(pkg_dir,"src","./tools/OL12_KDs_g63.json")
    dict_OL12_KDs_g63     = JSON.parsefile(file_path)
    file_path   = joinpath(pkg_dir,"src","./tools/OL12_KDs_l52.json")
    dict_OL12_KDs_l52     = JSON.parsefile(file_path)

    db_inf      = retrieve_solution_phase_information("ig");
    
    return dict_ss, hidden_pp, dict_em, dict_OL12_KDs_l52, dict_OL12_KDs_g63, dict_OL12_KDs_g52l63, db_inf
end

"""
    DB_MENU_GROUPS

    Database-selector layout: which databases appear in the dropdown, under which heading
    and in which order. Purely presentational - the databases themselves, their acronyms
    and their names come from `MAGEMin_C.MAGEMIN_DATABASES`. Dropping an acronym from
    here hides it from the interface without removing it from the library.
"""
const DB_MENU_GROUPS = [
    "- PUBLISHED DATABASE -"  => ["mp", "mb", "ig", "igd", "igad", "um"],
    "- BERMAN EOS DATABASE -" => ["po"],
    "- MANTLE DATABASE -"     => ["mtl", "sb11", "sb21", "sb24"],
    "- CUSTOM DATABASE -"     => ["ume", "mpe", "mbe", "all"],
]

"""
    DB_MENU_LABELS

    Shorter dropdown captions for databases whose full `MAGEMin_C` name does not fit the
    selector. Any acronym left out here is shown under its full name.
"""
const DB_MENU_LABELS = Dict(
    "ig"   => "Igneous (Green et al., 2025, after H18)",
    "igd"  => "Igneous dry (Su et al., 2026, after T21)",
    "ume"  => "Ultramafic extended (Evans & Frost., 2021)",
    "mpe"  => "Metapelite extended (White et al., 2014, Green et al., 2016, Evans & Frost., 2021)",
    "mbe"  => "Metabasite extended (Green et al., 2016, Diener et al., 2007)",
    "all"  => "Global TC dataset",
)

db_menu_label(dtb::String) = get(DB_MENU_LABELS, dtb, get_db_label(dtb))

"""
    DB_STAGED

    Database acronyms the interface already carries data for (predefined bulk-rock rows,
    commented-out selector entries) but which MAGEMin does not implement yet. They are
    accepted by the bulk-file importer so work in progress on them keeps loading; they
    are not in `DB_MENU_GROUPS`, so they stay out of the selector until the library
    grows them and they turn up in `get_db_list()` on their own.
"""
const DB_STAGED = ("igm", "cs")

function get_dtbulk_list()

    dtb_dict = Vector{Dict{String,Any}}()
    for (header, acronyms) in DB_MENU_GROUPS
        push!(dtb_dict, Dict{String,Any}("label" => header, "value" => "separator", "disabled" => true))
        for dtb in acronyms
            push!(dtb_dict, Dict{String,Any}("label" => db_menu_label(dtb), "value" => dtb))
        end
    end

    dba = DataFrame(        database     = String[],
                            acronym      = String[],
    )
    for dtb in get_db_list()
        push!(dba, Dict(    :database    => get_db_label(dtb),
                            :acronym     => dtb,
                            ), cols=:union)
    end

    # Predefined bulk-rock compositions live in user_data/predefined_bulks.csv, one row per
    # composition, in the same column layout the bulk-file importer accepts - add a row there
    # to add a composition, no code change needed.
    bulk_csv  = CSV.read(joinpath(pkg_dir, "user_data", "predefined_bulks.csv"), DataFrame)
    oxide_cols = [n for n in names(bulk_csv) if !(n in ("db","test","sysUnit","title","comments"))]

    db = DataFrame(         bulk        = String[],
                            title       = String[],
                            comments    = String[],
                            db          = String[],
                            test        = Int64[],
                            sysUnit     = String[],
                            oxide       = Array{String, 1}[],
                            frac        = Array{Float64, 1}[],
                            frac2       = Array{Float64, 1}[],
                            frac_wt     = Array{Float64, 1}[],
                            frac2_wt    = Array{Float64, 1}[],
                        )

    for r in eachrow(bulk_csv)
        present = [c for c in oxide_cols if !ismissing(r[c])]
        frac    = Float64[r[c] for c in present]
        push!(db, Dict( :bulk       => "predefined",
                        :title      => String(r.title),
                        :comments   => ismissing(r.comments) ? "" : String(r.comments),
                        :db         => String(r.db),
                        :test       => Int64(r.test),
                        :sysUnit    => String(r.sysUnit),
                        :oxide      => String.(present),
                        :frac       => frac,
                        :frac2      => copy(frac),
                        ), cols=:union)
    end

                
                            

    dbte = DataFrame(       composition = String[],
                            title       = String[],
                            comments    = String[],
                            test        = Int64[],
                            elements    = Array{String, 1}[],
                            μg_g        = Array{Float64, 1}[],
                            μg_g2       = Array{Float64, 1}[],
                    )   

    push!(dbte,Dict(    :composition=> "predefined",
                        :title      => "Tonalite",
                        :comments   => "J-F Moyen",
                        :test       => 0,
                        :elements   => ["CO2","S","P2O5","Rb", "Ba", "Th", "U", "Nb", "Ta", "La", "Ce", "Pb", "Pr", "Sr", "Nd", "Zr", "Hf", "Sm", "Eu", "Gd", "Tb", "Dy", "Y", "Ho", "Er", "Tm", "Yb", "Lu", "V", "Sc", "Cs", "K", "Ti"],
                        :μg_g        => round.([500.0,200.0,200.0,64.5373756, 499.0093971, 5.69152854, 1.064824497, 5.430265866, 0.722386615, 29.06202556, 53.78324684, 15.17205921, 5.797620808, 484.5753262, 20.54095673, 150.2402264, 3.95645511, 3.317738791, 0.961548784, 2.418869313, 0.315058021, 1.593968618, 7.459369222, 0.296925128, 0.799927928, 0.128677572, 0.713354049, 0.133287066, 39.87762745, 5.524762752, 3.5, 15000.0, 2800.0],digits=2),
                        :μg_g2       => round.([500.0,200.0,200.0,64.5373756, 499.0093971, 5.69152854, 1.064824497, 5.430265866, 0.722386615, 29.06202556, 53.78324684, 15.17205921, 5.797620808, 484.5753262, 20.54095673, 150.2402264, 3.95645511, 3.317738791, 0.961548784, 2.418869313, 0.315058021, 1.593968618, 7.459369222, 0.296925128, 0.799927928, 0.128677572, 0.713354049, 0.133287066, 39.87762745, 5.524762752, 3.5, 15000.0, 2800.0],digits=2),
                    ), cols=:union)


    push!(dbte,Dict(    :composition=> "predefined",
                        :title      => "Basalt",
                        :comments   => "J-F Moyen",
                        :test       => 1,
                        :elements   => ["CO2","S","P2O5","Rb", "Ba", "Th", "U", "Nb", "Ta", "La", "Ce", "Pb", "Pr", "Sr", "Nd", "Zr", "Hf", "Sm", "Eu", "Gd", "Tb", "Dy", "Y", "Ho", "Er", "Tm", "Yb", "Lu", "V", "Sc", "Cs", "K", "Ti"],
                        :μg_g        => round.([100.0,100.0,100.0,16.60777308, 122.8449739, 1.074692058, 0.290233271, 3.808354064, 0.330971265, 6.938172601, 16.04827796, 5.452969044, 2.253943183, 163.4533209, 10.18276823, 66.90677472, 1.841502082, 3.3471043, 0.915941652, 3.28230146, 1.417695298, 3.851230952, 20.74016207, 0.914966282, 2.20425, 0.343734976, 2.136202593, 0.323405135, 257.4346716, 38.23663423, 0.4, 2000.0, 7500.0],digits=2),
                        :μg_g2       => round.([100.0,100.0,100.0,16.60777308, 122.8449739, 1.074692058, 0.290233271, 3.808354064, 0.330971265, 6.938172601, 16.04827796, 5.452969044, 2.253943183, 163.4533209, 10.18276823, 66.90677472, 1.841502082, 3.3471043, 0.915941652, 3.28230146, 1.417695298, 3.851230952, 20.74016207, 0.914966282, 2.20425, 0.343734976, 2.136202593, 0.323405135, 257.4346716, 38.23663423, 0.4, 2000.0, 7500.0],digits=2),
                    ), cols=:union)


    push!(dbte,Dict(    :composition=> "predefined",
                        :title      => "Pyrolite (Primitive Mantle)",
                        :comments   => "McDonough and Sun, 1995",
                        :test       => 2,
                        :elements   => ["CO2","S","P2O5","Rb", "Ba", "Th", "U", "Nb", "Ta", "La", "Ce", "Pb", "Pr", "Sr", "Nd", "Zr", "Hf", "Sm", "Eu", "Gd", "Tb", "Dy", "Y", "Ho", "Er", "Tm", "Yb", "Lu", "V", "Sc", "Cs", "K", "Ti"],
                        :μg_g        => round.([50.0,50.0,50.0,0.6,6.6,0.0795,0.0203,0.658,0.037,0.648,1.675,0.150,0.254,19.9,1.25,10.5,0.283,0.406,0.154,0.544,0.099,0.674,4.30,0.149,0.438,0.068,0.441,0.0675,8.2,16.2,0.021,240.0,1205.0],digits=2),
                        :μg_g2       => round.([50.0,50.0,50.0,0.6,6.6,0.0795,0.0203,0.658,0.037,0.648,1.675,0.150,0.254,19.9,1.25,10.5,0.283,0.406,0.154,0.544,0.099,0.674,4.30,0.149,0.438,0.068,0.441,0.0675,8.2,16.2,0.021,240.0,1205.0],digits=2),
                    ), cols=:union)



    db.frac_wt  .= mol2wt.(db.frac,db.oxide)
    db.frac2_wt .= mol2wt.(db.frac2,db.oxide)

    for (i,val) in enumerate(db.frac_wt)
        db.frac_wt[i] = round.(val,digits= 6)
    end
    for (i,val) in enumerate(db.frac2_wt)
        db.frac2_wt[i] = round.(val,digits= 6)
    end

    return db, dba, dtb_dict, dbte
end
